In [25]:
import numpy as np
import pandas as pd

In [26]:
df_ords = pd.read_csv('df_ords_clean.csv')
df_prods = pd.read_csv('df_prods_clean.csv')

In [28]:
#Dropping the index columns from the df_ords dataframe
df_ords= df_ords.drop(['Unnamed: 0','Unnamed: 0.1'], axis=1)

In [49]:
df_ords.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,7.0
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

In [43]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [31]:
#Dropping the index columns from the df_prods dataframe

df_prods= df_prods.drop(['Unnamed: 0'], axis=1)

In [32]:
df_prods

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3
...,...,...,...,...,...
49667,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3
49668,49685,En Croute Roast Hazelnut Cranberry,42,1,3.1
49669,49686,Artisan Baguette,112,3,7.8
49670,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.7
49671,49688,Fresh Foaming Cleanser,73,11,13.5

In [34]:
df_ords_prior = pd.read_csv('/content/order_products__prior.csv')

In [44]:
df_ords_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [36]:
df_ords.shape

(3421083, 6)

In [37]:
df_ords_prior.shape

(32434489, 4)

In [39]:
# Merging the df_ords and df_ords_prior dataframes 

df_merged_large = df_ords.merge(df_ords_prior, on = 'order_id', indicator = True)

In [41]:
df_merged_large.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,2539329,1,1,2,8,7.0,196,1,0,both
1,2539329,1,1,2,8,7.0,14084,2,0,both
2,2539329,1,1,2,8,7.0,12427,3,0,both
3,2539329,1,1,2,8,7.0,26088,4,0,both
4,2539329,1,1,2,8,7.0,26405,5,0,both

In [45]:
df_merged_large['_merge'].value_counts()

both          32434489
left_only            0
right_only           0
Name: _merge, dtype: int64

In [46]:
df_merged_large.shape

(32434489, 10)

In [47]:
from google.colab import files

df_merged_large.to_pickle('orders_products_combined.pkl') 
files.download('orders_products_combined.pkl')

In [48]:
df_merged_large.to_csv('orders_products_combined.csv') 
files.download('orders_products_combined.csv')

In [50]:
files.download('orders_products_combined.csv')